export const APP_NAME = "Resource Center";
export const API_URL = "http://db.resourcecenter.local/wp-json/wp/v2/";

/* REDUX ACTIONS */
/** Filter click event actions **/
export const FILTER_ADD = "FILTER_ADD";
export const FILTER_REMOVE = "FILTER_REMOVE";

/** Get Post Actions **/
export const GET_POSTS_STARTED = "GET_POSTS_STARTED";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

/** Get taxonomy actions **/
export const GET_INDUSTRY_STARTED = "GET_INDUSTRY_STARTED";
export const GET_INDUSTRY_SUCCESS = "GET_INDUSTRY_SUCCESS";
export const GET_INDUSTRY_FAILURE = "GET_INDUSTRY_FAILURE";

export const GET_SOLUTIONS_STARTED = "GET_SOLUTIONS_STARTED";
export const GET_SOLUTIONS_SUCCESS = "GET_SOLUTIONS_SUCCESS";
export const GET_SOLUTIONS_FAILURE = "GET_SOLUTIONS_FAILURE";

export const GET_RESOURCE_TYPE_STARTED = "GET_RESOURCE_TYPE_STARTED";
export const GET_RESOURCE_TYPE_SUCCESS = "GET_RESOURCE_TYPE_SUCCESS";
export const GET_RESOURCE_TYPE_FAILURE = "GET_RESOURCE_TYPE_FAILURE";

/** Get taxonomy terms actions **/
export const GET_INDUSTRY_TERMS_STARTED = "GET_INDUSTRY_TERMS_STARTED";
export const GET_INDUSTRY_TERMS_SUCCESS = "GET_INDUSTRY_TERMS_SUCCESS";
export const GET_INDUSTRY_TERMS_FAILURE = "GET_INDUSTRY_TERMS_FAILURE";

export const GET_SOLUTIONS_TERMS_STARTED = "GET_SOLUTIONS_TERMS_STARTED";
export const GET_SOLUTIONS_TERMS_SUCCESS = "GET_SOLUTIONS_TERMS_SUCCESS";
export const GET_SOLUTIONS_TERMS_FAILURE = "GET_SOLUTIONS_TERMS_FAILURE";

export const GET_RESOURCE_TYPE_TERMS_STARTED = "GET_RESOURCE_TYPE_TERMS_STARTED";
export const GET_RESOURCE_TYPE_TERMS_SUCCESS = "GET_RESOURCE_TYPE_TERMS_SUCCESS";
export const GET_RESOURCE_TYPE_TERMS_FAILURE = "GET_RESOURCE_TYPE_TERMS_FAILURE";